spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
  storage:
    s3:
      region: ${AWS_REGION}
      bucket: ${S3_BUCKET}
      presign-ttl: ${S3_PRESIGN_TTL:5m}
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
